# fly.toml file generated for protohackers-elixir-v0 on 2023-01-12T03:16:17-05:00

app = "protohackers-elixir-v0"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 5001
  processes = ["app"]
  protocol = "tcp"

	[services.concurrency]
		hard_limit = 25
		soft_limit = 20
		type = "connections"

	[[services.ports]]
		handlers = []
		port = "5001"

	[[services.tcp_checks]]
		grace_period = "1s"
		interval = "15s"
		restart_limit = 0
		timeout = "2s"
